Move serviceworker registration from footer to index;
Because the footer is included in many templates on many urls,
it resulted in a TypeError when not on the index/root domain:
TypeError: Failed to register a ServiceWorker:
A bad HTTP response code (404) was received when fetching the script.